#ifndef BALANCE_H
#define BALANCE_H
/* Tunable mechanics. Trait costs/effects and milestone thresholds live in their
   definition tables; geometry, node counts, and codec widths are not balance. */
#define PROB_SCALE 10000U
#define START_DNA 12
#define REGION_REWARD 5
#define AFFECTED_REWARD 8
#define DEATH_REWARD 10
#define MAX_DNA (START_DNA + 7 * REGION_REWARD + 9 * AFFECTED_REWARD + 6 * DEATH_REWARD)
#define BASE_INFECTIVITY 12
#define DEVOLVE_COST 4
#define VIRUS_DEVOLVE_COST 7
#define ADAPTATION_REDUCTION 45
#define HARDENING_REDUCTION 30
#define BASE_TRAVEL 800
#define TRANSPORT_LEVEL_BONUS 1200
#define AEROSOL_TRAVEL_BONUS 1000
#define FUNGUS_TRAVEL_DIVISOR 2
#define BIRD_LEVEL_CHANCE 100
#define VECTOR_MIGRATION_BONUS 200
#define HEAT_PENALTY 100
#define COLD_PENALTY 180
#define MEDICAL_PENALTY 100
#define AIR_WATER_SPREAD_BONUS 220
#define ANIMAL_VECTOR_SPREAD_BONUS 280
#define BLOOD_SPREAD_BONUS 50
#define BLOOD_HEALTHCARE_BONUS 100
#define AEROSOL_SPREAD_BONUS 300
#define RESERVOIR_SPREAD_BONUS 600
#define RESERVOIR_SPARSE_BONUS 100
#define VECTOR_COLD_BONUS 280
#define MIN_SPREAD 100
#define DISCOVERY_LIMIT 12000U
#define DISCOVERY_ACTIVE_THRESHOLD 65
#define DISCOVERY_DEATH_THRESHOLD 5
#define DISCOVERY_HEALTHCARE_DIVISOR 8
#define DISCOVERY_SEVERITY_WEIGHT 2
#define DISCOVERY_DEATH_WEIGHT 8
#define RESEARCH_DELAY 8
#define RESEARCH_FRACTION_SCALE 200U
#define RESEARCH_BASE 20
#define RESEARCH_ACTIVE_DIVISOR 2
#define RESEARCH_SEVERITY_WEIGHT 2
#define RESEARCH_REGION_WEIGHT 3
#define RESPONSE_CURE_THRESHOLD 2500
#define RESPONSE_SEVERITY_THRESHOLD 30
#define RESPONSE_DEATH_THRESHOLD 10
#define CLOSURE_ACTIVE_DIVISOR 10
#define CLOSURE_ESCALATION_BONUS 10
#define PORT_CLOSURE_CHANCE 800
#define MIGRATION_INTERVAL 8
#define MUTATION_INTERVAL 12
#define MUTATION_CHANCE 1500
#endif
